### ISSUE TITLE
試作ケースのコード名ルール

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/Cases#2]
試作ケースのコード名ルールの策定をする

**Comment by tadfmac** [comment]
# コード名の命名について

コード名の命名ルールについて、案を書きます。ご指摘等お待ちしています。
基本的には必要最低限にしたいというのが希望です。
1. コード名はケース作者（デザイナー）が任意の段階で決める。先に決めておくことが望ましい
2. コード名に商標等権利が発生する言葉を含めてはならない（「CHIRIMEN」も含めて）
3. コード名に公序良俗に反する言葉を含めてはならない
4. コード名に既に登録されている他のケースと全く同じ名前は使わない
5. コード名に利用可能な文字は英数字及び`-`、`_`のみとする

# その他

## フォルダ名とreadme.md

コード名とは別ですが必要最低限という意味で下記を入れた方がいいとおもいます。
- フォルダ名はコード名とする
- フォルダ名の直下に`readme.md`を配置する 

`readme.md`にはケースの設計情報や作り方などの情報の他に、
1. ケースのコード名
2. 作者（デザイナー）
3. ステータス（作成中なのか、作成完了なのか）
4. ライセンス
5. ケースの簡単な紹介（特徴など）

を記載した方が良いとおもいます。

**Comment by gurezo** [comment]
上記５と似ていますが、ケースの組み立てマニュアルも有った方が良いと思います。

**Comment by tadfmac** [comment]
とりあえず、ルールBookはwikiにでも移動してCloseしませんか?

**Comment by gurezo** [comment]
直下のREADMEに追記したので、close
